### ISSUE TITLE
firfox, the buttons and the bottom banner have merged as one 

### ISSUE THREAD

**Issue by DaraVakili** [salutare-group/Test-Request-Public#16]
![image](https://user-images.githubusercontent.com/30321950/110816091-f011f480-8282-11eb-9e38-7a8e84b7268d.png)

**Comment by RyanJP18** [comment]
This is also on Chrome so will need fixing, but is actually a side effect of this bug: https://github.com/salutare-group/clearinghouse-front/issues/107
