### ISSUE TITLE
Firefox Issues

### ISSUE THREAD

**Issue by RussellJTh** [salutare-group/Test-Request-Public#2]
![image](https://user-images.githubusercontent.com/76914359/109183057-79a2cc00-7785-11eb-86c4-44f17914b5bc.png)
![image](https://user-images.githubusercontent.com/76914359/109183153-90492300-7785-11eb-93c4-179f33946449.png)
Searching for a patient does not give a tick
Error when pressing print A4
Clicking on date of birth on find patient left hand search bar gives XML parse error
Tried to add new user with bogus info - error code did not say what was wrong

**Comment by RyanJP18** [comment]
We don't support firefox so I will close this issue. Please reopen if it persists on Chrome.
