### ISSUE TITLE
Long wait times if large patient data set returned

### ISSUE THREAD

**Issue by dialch** [salutare-group/Test-Request-Public#27]
On the RFL internal staging build, currently deployed

If we search for a name like 'Patel' with many entries, then the pause is quite long - and nothing happens or indicates that something is working. There were about 336 entries - 33 pages worth. Let's find a better way to indicate and handle the wait times or truncate the search results.

**Comment by RyanJP18** [comment]
I think we should probably show a spinner in the loading area until the load is done (eventually, a loading bar may be better, but this would be an expensive change at this point)

@dialch  could you also run this search on a super common name such as "John" and give me a rough time taken? I think if it's longer than 5 seconds we will need to truncate and show some kind of notification on the page like "Showing the first 1000 results of xxxx, please provide a more specific search."

**Comment by RyanJP18** [comment]
Will pick up the loading spinner part as a different enhancement ticket https://github.com/salutare-group/clearinghouse-front/issues/165
