### ISSUE TITLE
Edit team button shows up when you are member and staff

### ISSUE THREAD

**Issue by benjalon** [salutare-group/Test-Request-Public#28]

**Comment by RyanJP18** [comment]
Honestly I have no idea what the behaviour of these teams permissions quirks are anymore. @RussellJTh  can you verify this is indeed a permissions check bug? I will assign labels as if this is the case.

**Comment by RyanJP18** [comment]
@benjalon It only shows up when you're staff, not a member. Staff seem to have the ability to Add and delete teams already. and edit teams so this seems to be correct behaviour.

I think part of the confusion is coming from the fact that the default member account is actually staff, but mis-labeled as member. It seems that if you set someone to be staff, it always displays them as member regardless.
