### ISSUE TITLE
After asking for password reset - leaves me on reset page

### ISSUE THREAD

**Issue by dialch** [salutare-group/Test-Request-Public#29]
should take me back to login page

![image](https://user-images.githubusercontent.com/69807360/112622088-d1872e00-8e2a-11eb-8590-a9a0d156584a.png)

**Comment by RyanJP18** [comment]
This becomes a dead tab after the link is sent because the flow picks up from the email rather than this page.

Instead, I think we should display a popup which simply says:
"Please check your email for the password reset link", then if the user hits okay on that, it redirects to the home page
