### ISSUE TITLE
Clicking 'reset all' and last patient stays in Patient table

### ISSUE THREAD

**Issue by dialch** [salutare-group/Test-Request-Public#32]
![image](https://user-images.githubusercontent.com/69807360/112622722-b5d05780-8e2b-11eb-8a56-c8216371b9a8.png)

**Comment by dialch** [comment]
clicking Reset a second time did remove the patient record from top table.

**Comment by RyanJP18** [comment]
I changed this recently so I must've introduced this bug

**Comment by RyanJP18** [comment]
Turns out this is related to a race condition with input fields and double submit problems, I've fixed this is a branch that hasn't been merged yet
