### ISSUE TITLE
Error on Add New User close

### ISSUE THREAD

**Issue by dialch** [salutare-group/Test-Request-Public#36]
I didn't add a new user after going to the Add New User dialog box - I just clicked on 'cancel' - and it popped an error. 

![image](https://user-images.githubusercontent.com/69807360/112623842-2461e500-8e2d-11eb-95af-8345f6d4e243.png)

**Comment by RyanJP18** [comment]
Nice spot

One for @RussellJTh I think. Should just be some missing validation on popup submission.
