### ISSUE TITLE
Printing issue with multiple teams

### ISSUE THREAD

**Issue by aesposito1** [salutare-group/Test-Request-Public#38]
If there are multiple teams to chose from when logging in, the first team presented in the dropdown bit is not actually selected.

![image](https://user-images.githubusercontent.com/72013581/112832941-edd6d500-908d-11eb-8bda-7d2b1184e197.png)

Therefore there is not team id for the default printer, which means printing is not possible:

![image](https://user-images.githubusercontent.com/72013581/112826653-30e07a80-9085-11eb-9a1c-c1e49a06b435.png)

**Comment by aesposito1** [comment]
It does for other team members but not admin@salutare?

**Comment by aesposito1** [comment]
PROBLEM: Salutare is the first team on the drop down, so if this is the team you want to log in as then you press ok - but just because it shows on the drop down does not mean that it is the selected team, as the api route for the team id is 'undefined'

**Comment by RyanJP18** [comment]
Good spot

**Comment by RyanJP18** [comment]
This likely affects all drop down menus
