### ISSUE TITLE
No way of knowing which team you're logged in as

### ISSUE THREAD

**Issue by aesposito1** [salutare-group/Test-Request-Public#39]
Once you're logged in there's no reference to which team you're acting as a member of

**Comment by RyanJP18** [comment]
This refers to the session team you log in with in the case of a user belonging to multiple teams. It's unrelated to the team display on the teams panel.

@dialch I think we should have Sergio decide where he'd like us to display this. Perhaps undernearth the username in the nav bar? Something like:

(avatar_img) Chris Dial 
(avatar_img) @Royal Free London

**Comment by RyanJP18** [comment]
The mechanism is in place as I described above and we can file an enhancement ticket if we want it moved / restyled
