### ISSUE TITLE
Orders don't appear after reset

### ISSUE THREAD

**Issue by aesposito1** [salutare-group/Test-Request-Public#9]
I found benny omar's orders, then I reset the page and searched benny again. The orders did not come up again

![image](https://user-images.githubusercontent.com/72013581/110796114-82a89880-826f-11eb-91e7-652376523103.png)

**Comment by aesposito1** [comment]
@RyanJP18 Yup it's still happening. Just checked and it's on development too so not just limited to staging

**Comment by RyanJP18** [comment]
Thanks!

**Comment by RyanJP18** [comment]
This is caused by a race condition between resetting fields and submitting searches. My new input ref changes will fix this but that branch won't be finished for while yet.
